# Generated by Django 4.2.13 on 2024-07-30 20:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergy_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ChatChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generation_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DrSpecialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('content', models.CharField(max_length=300)),
                ('feedback_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(default=0.0)),
                ('height', models.FloatField(default=0.0)),
                ('date_changed', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SavoirUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=255)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('registration_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_delete', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.IntegerField(default=0)),
                ('is_superuser', models.BooleanField(default=False)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='UserFullName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forenames', models.TextField(max_length=400)),
                ('surname', models.TextField(max_length=200)),
                ('gender', models.ForeignKey(blank=True, default=5, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_gender', to='patients.gender')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='patients.savoiruser')),
            ],
        ),
        migrations.CreateModel(
            name='UnspecifiedSymptoms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Q1', models.BooleanField()),
                ('Q2', models.BooleanField()),
                ('Q3', models.BooleanField()),
                ('Q4', models.BooleanField()),
                ('Q5', models.BooleanField()),
                ('Q6', models.BooleanField()),
                ('Q7', models.BooleanField()),
                ('Q8', models.BooleanField()),
                ('Q9', models.BooleanField()),
                ('Q10', models.BooleanField()),
                ('Q11', models.BooleanField()),
                ('Q12', models.BooleanField()),
                ('Q13', models.BooleanField()),
                ('Q14', models.BooleanField()),
                ('Q15', models.BooleanField()),
                ('other_symptom', models.CharField(max_length=300)),
                ('generation_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='patients.savoiruser')),
            ],
        ),
        migrations.CreateModel(
            name='PtExercisePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_num', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)])),
                ('day_num', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)])),
                ('exercise', models.TextField()),
                ('generated_time', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.savoiruser')),
            ],
        ),
        migrations.CreateModel(
            name='PtDietRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement', models.TextField(max_length=150)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='patients.savoiruser')),
            ],
        ),
        migrations.CreateModel(
            name='PtDietPlanApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_status', models.BooleanField(default=False)),
                ('approval_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.savoiruser')),
            ],
        ),
        migrations.CreateModel(
            name='PtDietPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_num', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)])),
                ('day_num', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)])),
                ('meal_num', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)])),
                ('meal', models.TextField()),
                ('generated_time', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.savoiruser')),
            ],
        ),
        migrations.CreateModel(
            name='PtDiagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.TextField()),
                ('generation_time', models.DateTimeField(auto_now_add=True)),
                ('diagnosed_dr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dr_diagnosis', to='patients.savoiruser')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pt_diagnosis', to='patients.savoiruser')),
            ],
        ),
        migrations.CreateModel(
            name='PtAllergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.allergy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.savoiruser')),
            ],
        ),
        migrations.CreateModel(
            name='PMHForRec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.condition')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='PatientOtherAllergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otherAllergy', models.TextField(max_length=300)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='patients.savoiruser')),
            ],
        ),
        migrations.CreateModel(
            name='PatientBirthday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='patients.savoiruser')),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.savoiruser'),
        ),
        migrations.CreateModel(
            name='PastRelatedHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Q1', models.BooleanField()),
                ('Q2', models.BooleanField()),
                ('Q3', models.BooleanField()),
                ('Q4', models.BooleanField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Nutritionist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification', models.CharField(max_length=255)),
                ('experience_years', models.PositiveIntegerField()),
                ('is_authenticated', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='patients.savoiruser')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.chatchannel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.savoiruser')),
            ],
        ),
        migrations.CreateModel(
            name='LungCancerSymptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Q1', models.IntegerField()),
                ('Q2', models.IntegerField()),
                ('Q3', models.IntegerField()),
                ('Q4', models.IntegerField()),
                ('Q5', models.IntegerField()),
                ('Q6', models.IntegerField()),
                ('Q7', models.IntegerField()),
                ('Q8', models.IntegerField()),
                ('Q9', models.IntegerField()),
                ('Q10', models.IntegerField()),
                ('Q11', models.IntegerField()),
                ('Q12', models.IntegerField()),
                ('Q13', models.IntegerField()),
                ('Q14', models.IntegerField()),
                ('Q15', models.IntegerField()),
                ('Q16', models.IntegerField()),
                ('Q17', models.IntegerField()),
                ('Q18', models.IntegerField()),
                ('Q19', models.IntegerField()),
                ('Q20', models.IntegerField()),
                ('Q21', models.IntegerField()),
                ('Q22', models.IntegerField()),
                ('Q23', models.IntegerField()),
                ('result', models.IntegerField()),
                ('generation_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='patients.savoiruser')),
            ],
        ),
        migrations.CreateModel(
            name='FamilyHistoryForRec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.condition')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField()),
                ('is_available', models.BooleanField(default=True)),
                ('dr_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.savoiruser')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=255)),
                ('seniority', models.CharField(max_length=255)),
                ('experience_years', models.PositiveIntegerField()),
                ('is_authenticated', models.BooleanField(default=False)),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.drspecialty')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='patients.savoiruser')),
            ],
        ),
        migrations.CreateModel(
            name='DiagnosisReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_date', models.DateTimeField()),
                ('is_delete', models.BooleanField(default=False)),
                ('dr_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dr_reservations', to='patients.savoiruser')),
                ('pt_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pt_reservations', to='patients.savoiruser')),
            ],
        ),
        migrations.AddField(
            model_name='chatchannel',
            name='pt_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pt_message', to='patients.savoiruser'),
        ),
        migrations.AddField(
            model_name='chatchannel',
            name='staff_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_message', to='patients.savoiruser'),
        ),
        migrations.CreateModel(
            name='CancerSymptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Q1', models.BooleanField()),
                ('Q2', models.BooleanField()),
                ('Q3', models.BooleanField()),
                ('Q4', models.BooleanField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='BreastCancerSymptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Q1', models.IntegerField()),
                ('Q2', models.IntegerField()),
                ('Q3', models.IntegerField()),
                ('Q4', models.IntegerField()),
                ('Q5', models.IntegerField()),
                ('Q6', models.IntegerField()),
                ('Q7', models.IntegerField()),
                ('Q8', models.IntegerField()),
                ('Q9', models.IntegerField()),
                ('Q10', models.IntegerField()),
                ('Q11', models.IntegerField()),
                ('Q12', models.IntegerField()),
                ('Q13', models.IntegerField()),
                ('Q14', models.IntegerField()),
                ('Q15', models.IntegerField()),
                ('Q16', models.IntegerField()),
                ('result', models.IntegerField()),
                ('generation_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='patients.savoiruser')),
            ],
        ),
        migrations.CreateModel(
            name='BowelCancerSymptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Q1', models.IntegerField()),
                ('Q2', models.IntegerField()),
                ('Q3', models.IntegerField()),
                ('Q4', models.IntegerField()),
                ('Q5', models.IntegerField()),
                ('Q6', models.IntegerField()),
                ('Q7', models.IntegerField()),
                ('Q8', models.IntegerField()),
                ('Q9', models.IntegerField()),
                ('Q10', models.IntegerField()),
                ('Q11', models.IntegerField()),
                ('Q12', models.IntegerField()),
                ('Q13', models.IntegerField()),
                ('Q14', models.IntegerField()),
                ('Q15', models.IntegerField()),
                ('Q16', models.IntegerField()),
                ('Q17', models.IntegerField()),
                ('Q18', models.IntegerField()),
                ('result', models.IntegerField()),
                ('generation_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='patients.savoiruser')),
            ],
        ),
        migrations.CreateModel(
            name='AIPredictionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)])),
                ('generation_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.savoiruser')),
            ],
        ),
        migrations.CreateModel(
            name='AIPatientRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation', models.TextField()),
                ('date_issued', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='AICancerPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction', models.TextField()),
                ('date_issued', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
        ),
    ]
