# Generated by Django 4.2.13 on 2024-08-03 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProstateCancerSymptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Q1', models.IntegerField()),
                ('Q2', models.IntegerField()),
                ('Q3', models.IntegerField()),
                ('Q4', models.IntegerField()),
                ('Q5', models.IntegerField()),
                ('Q6', models.IntegerField()),
                ('Q7', models.IntegerField()),
                ('Q8', models.IntegerField()),
                ('Q9', models.IntegerField()),
                ('Q10', models.IntegerField()),
                ('Q11', models.IntegerField()),
                ('Q12', models.IntegerField()),
                ('Q13', models.IntegerField()),
                ('Q14', models.IntegerField()),
                ('Q15', models.IntegerField()),
                ('Q16', models.IntegerField()),
                ('result', models.IntegerField()),
                ('generation_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='patients.savoiruser')),
            ],
        ),
        migrations.CreateModel(
            name='OvarianCancerSymptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Q1', models.IntegerField()),
                ('Q2', models.IntegerField()),
                ('Q3', models.IntegerField()),
                ('Q4', models.IntegerField()),
                ('Q5', models.IntegerField()),
                ('Q6', models.IntegerField()),
                ('Q7', models.IntegerField()),
                ('Q8', models.IntegerField()),
                ('Q9', models.IntegerField()),
                ('Q10', models.IntegerField()),
                ('Q11', models.IntegerField()),
                ('Q12', models.IntegerField()),
                ('Q13', models.IntegerField()),
                ('Q14', models.IntegerField()),
                ('Q15', models.IntegerField()),
                ('Q16', models.IntegerField()),
                ('Q17', models.IntegerField()),
                ('result', models.IntegerField()),
                ('generation_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='patients.savoiruser')),
            ],
        ),
    ]
