# Generated by Django 5.0.6 on 2024-08-02 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_rename_created_at_dietarypreferences_createdat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dietarypreferences',
            name='glutenFree',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='dietarypreferences',
            name='halal',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='dietarypreferences',
            name='kosher',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='dietarypreferences',
            name='lactoseFree',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='dietarypreferences',
            name='other',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='dietarypreferences',
            name='pescatarian',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='dietarypreferences',
            name='vegan',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='dietarypreferences',
            name='vegetarian',
            field=models.BooleanField(),
        ),
    ]
