# Generated by Django 5.0.7 on 2024-08-23 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_prostatecancersymptom_ovariancancersymptom'),
        ('patients', '0004_alter_dietarypreferences_glutenfree_and_more'),
    ]

    operations = [
    ]
