# Generated by Django 5.0.7 on 2024-08-23 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_merge_20240823_1935'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unspecifiedsymptoms',
            old_name='Q1',
            new_name='AbdoPain',
        ),
        migrations.RenameField(
            model_name='unspecifiedsymptoms',
            old_name='Q10',
            new_name='Anorexia',
        ),
        migrations.RenameField(
            model_name='unspecifiedsymptoms',
            old_name='Q11',
            new_name='BleedingBruising',
        ),
        migrations.RenameField(
            model_name='unspecifiedsymptoms',
            old_name='Q12',
            new_name='BowelBladderChanges',
        ),
        migrations.RenameField(
            model_name='unspecifiedsymptoms',
            old_name='Q13',
            new_name='Cough',
        ),
        migrations.RenameField(
            model_name='unspecifiedsymptoms',
            old_name='Q14',
            new_name='Dysphagia',
        ),
        migrations.RenameField(
            model_name='unspecifiedsymptoms',
            old_name='Q15',
            new_name='Fatigue',
        ),
        migrations.RenameField(
            model_name='unspecifiedsymptoms',
            old_name='Q2',
            new_name='Fever',
        ),
        migrations.RenameField(
            model_name='unspecifiedsymptoms',
            old_name='Q3',
            new_name='Lumps',
        ),
        migrations.RenameField(
            model_name='unspecifiedsymptoms',
            old_name='Q4',
            new_name='Lymphoedema',
        ),
        migrations.RenameField(
            model_name='unspecifiedsymptoms',
            old_name='Q5',
            new_name='NeuroSymptoms',
        ),
        migrations.RenameField(
            model_name='unspecifiedsymptoms',
            old_name='Q6',
            new_name='NightSweats',
        ),
        migrations.RenameField(
            model_name='unspecifiedsymptoms',
            old_name='Q7',
            new_name='Pain',
        ),
        migrations.RenameField(
            model_name='unspecifiedsymptoms',
            old_name='Q8',
            new_name='SkinChanges',
        ),
        migrations.RenameField(
            model_name='unspecifiedsymptoms',
            old_name='Q9',
            new_name='WeightLoss',
        ),
    ]
